//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTROS
    {
        public CENTROS()
        {
            this.CICLOSCENTRO = new HashSet<CICLOSCENTRO>();
            this.MODULOS = new HashSet<MODULOS>();
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public int IDCENTRO { get; set; }
        public string RUTEMPRESA { get; set; }
        public string NOMBRECENTRO { get; set; }
        public string COLUMN_4 { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
        public virtual ICollection<CICLOSCENTRO> CICLOSCENTRO { get; set; }
        public virtual ICollection<MODULOS> MODULOS { get; set; }
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
}
