//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLOSCENTRO
    {
        public int IDCICLO { get; set; }
        public Nullable<int> IDCENTRO { get; set; }
        public string JEFECENTRO { get; set; }
        public string ASISTENTECENTRO { get; set; }
        public string ENCARGADOREDES { get; set; }
        public string DESCCICLO { get; set; }
        public System.DateTime INICIOCICLO { get; set; }
        public System.DateTime FINCICLO { get; set; }
        public Nullable<bool> VIGENCIACICLO { get; set; }
    
        public virtual CENTROS CENTROS { get; set; }
    }
}
