//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS
    {
        public EMPRESAS()
        {
            this.CENTROS = new HashSet<CENTROS>();
            this.PERSONAS = new HashSet<PERSONAS>();
        }
    
        public string RUTEMPRESA { get; set; }
        public string RAZONSOCIAL { get; set; }
    
        public virtual ICollection<CENTROS> CENTROS { get; set; }
        public virtual ICollection<PERSONAS> PERSONAS { get; set; }
    }
}
