//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDIDARED
    {
        public MEDIDARED()
        {
            this.TIPORED = new HashSet<TIPORED>();
        }
    
        public int IDMEDIDARED { get; set; }
        public string NOMMEDIDA { get; set; }
        public string DESCMEDIDA { get; set; }
    
        public virtual ICollection<TIPORED> TIPORED { get; set; }
    }
}
