//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTORED
    {
        public int IDMOVIMIENTORED { get; set; }
        public Nullable<int> IDRED { get; set; }
        public Nullable<int> IDJAULA { get; set; }
        public Nullable<int> IDMOVIMIENTO { get; set; }
        public Nullable<bool> IMPREGNADO { get; set; }
        public Nullable<bool> LIMPIADO { get; set; }
        public Nullable<bool> DESINFECTADO { get; set; }
        public Nullable<System.DateTime> GARANTIA { get; set; }
        public Nullable<System.DateTime> FECHAMAR { get; set; }
        public Nullable<System.DateTime> FECHATRASLADO { get; set; }
    
        public virtual JAULA JAULA { get; set; }
        public virtual MOVIMIENTO MOVIMIENTO { get; set; }
        public virtual RED RED { get; set; }
    }
}
