//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONAS
    {
        public string RUTPERSONA { get; set; }
        public string RUTEMPRESA { get; set; }
        public string NOMBRESPERSONA { get; set; }
        public string APEPATERNO { get; set; }
        public string APEMATERNO { get; set; }
        public string CARGOPERSONA { get; set; }
        public Nullable<bool> VIGENCIAPERSONA { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
    }
}
