//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RED
    {
        public RED()
        {
            this.CROTAL = new HashSet<CROTAL>();
            this.MOVIMIENTORED = new HashSet<MOVIMIENTORED>();
        }
    
        public int IDRED { get; set; }
        public Nullable<int> IDTIPORED { get; set; }
        public string RUTTALLER { get; set; }
        public Nullable<decimal> TENSIOMETRIAINICIAL { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public Nullable<int> COSTOINICIAL { get; set; }
        public Nullable<bool> VIGENCIARED { get; set; }
        public Nullable<System.DateTime> FECHACAMBIO { get; set; }
    
        public virtual ICollection<CROTAL> CROTAL { get; set; }
        public virtual ICollection<MOVIMIENTORED> MOVIMIENTORED { get; set; }
        public virtual TALLER TALLER { get; set; }
        public virtual TIPORED TIPORED { get; set; }
    }
}
