//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOBUCEO
    {
        public SERVICIOBUCEO()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
        }
    
        public int IDSERVICIO { get; set; }
        public string RUTSERVICIO { get; set; }
        public string NOMBRESERVICIO { get; set; }
        public string ENCARGADOSERVICIO { get; set; }
        public string CIUDADSERVICIO { get; set; }
        public string DIRECCIONSERVICIO { get; set; }
        public string FONOSERVICIO { get; set; }
        public string EMAILSERVICIO { get; set; }
        public Nullable<bool> VIGENCIASERVICIO { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
    }
}
