//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALLER
    {
        public TALLER()
        {
            this.MOVIMIENTO = new HashSet<MOVIMIENTO>();
            this.RED = new HashSet<RED>();
        }
    
        public string RUTTALLER { get; set; }
        public string NOMBRETALLER { get; set; }
        public string CONTACTOTALLER { get; set; }
        public string CIUDADTALLER { get; set; }
        public string DIRECCIONTALLER { get; set; }
        public string FONOTALLER { get; set; }
        public string EMAILTALLER { get; set; }
        public Nullable<bool> VIGENCIATALLER { get; set; }
    
        public virtual ICollection<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual ICollection<RED> RED { get; set; }
    }
}
