//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazaNet.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPORED
    {
        public TIPORED()
        {
            this.RED = new HashSet<RED>();
        }
    
        public int IDTIPORED { get; set; }
        public string NOMTIPORED { get; set; }
        public int IDDENIER { get; set; }
        public int IDMEDIDARED { get; set; }
        public int IDTELA { get; set; }
        public int IDABERTURARED { get; set; }
        public int IDFUNCIONRED { get; set; }
        public Nullable<int> IDFIGURA { get; set; }
        public Nullable<bool> ZIPPET { get; set; }
        public Nullable<decimal> TENSIONSTANDAR { get; set; }
        public Nullable<decimal> TESNSIONMINIMA { get; set; }
        public Nullable<int> PERIODOESTANDAR { get; set; }
    
        public virtual ABERTURARED ABERTURARED { get; set; }
        public virtual DENIERRED DENIERRED { get; set; }
        public virtual FIGURARED FIGURARED { get; set; }
        public virtual FUNCIONRED FUNCIONRED { get; set; }
        public virtual MEDIDARED MEDIDARED { get; set; }
        public virtual ICollection<RED> RED { get; set; }
        public virtual TELARED TELARED { get; set; }
    }
}
